### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by CamilleScholtz** [One-com/digest#1]
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/One-com/digest.digestParts(0xc420124100, 0xc420152000, 0xc420152000)
    /home/onodera/wrk/src/github.com/One-com/digest/digest.go:208 +0x508
github.com/One-com/digest.(*Client).Do(0xc42004ddb0, 0xc420124100, 0xc, 0x83fe81, 0x10)
    /home/onodera/wrk/src/github.com/One-com/digest/digest.go:182 +0x169
main.walletRequest(0x83d55f, 0xa, 0x799d60, 0xc420018650, 0x0, 0x0)
    /home/onodera/wrk/src/github.com/onodera-punpun/sako/wallet.go:57 +0x234
main.bal(0x0, 0x0, 0x412568, 0x60)
    /home/onodera/wrk/src/github.com/onodera-punpun/sako/wallet.go:75 +0x65
main.main()
    /home/onodera/wrk/src/github.com/onodera-punpun/sako/main.go:27 +0x9b
```

Not exactly sure what's wrong here? I'm using code that's pretty much the same as the example.

**Comment by adamhassel** [comment]
It seems your server doesn't use correct RFC 2616 headers, where list elements are enclosed in `"`. Could you double check the format of your server's `WWW-Authenticate` header?

**Comment by CamilleScholtz** [comment]
You seem to be right, it sends `algorithm=MD5` instead of `algorithm="MD5"`. Since this does't seen to be your bug I'll close it this issue :)
